### ISSUE TITLE
Tratamento de dados enviado no body das requisições

### ISSUE THREAD

**Issue by victorers1** [AndreonSM/notAutumn#3]
## Problem

É possível cadastar um usuário com valores nulos de nome e mail.

## Print

![desafio2 - valores nulos](https://user-images.githubusercontent.com/13920100/157347724-9b3a5e78-4328-4a40-bf72-fdf6e5dde71e.png)

## Suggestion

Não cadastrar usuário caso dados não sejam passados. Retornar status [HTTP 400](https://developer.mozilla.org/pt-BR/docs/Web/HTTP/Status/400) caso dados enviados estejam incorretos.

**Comment by AndreonSM** [comment]
Solução para tratamento de dados nulos: 
Criar lógica, no método **_addUser_**, que identifique o caso em que dados não sejam passados e ignorar a requisição, neste caso; 
Usar _ResponseEntity_ para manipular o status para **_BAD_REQUEST_**.

Print:
![Issue3](https://user-images.githubusercontent.com/54782540/157740194-7be25bd3-cf10-4b54-91e4-33c62630c9a6.PNG)
