### ISSUE TITLE
HTTP Status ao criar item no banco

### ISSUE THREAD

**Issue by victorers1** [AndreonSM/notAutumn#4]
## Problem

Padrão REST não está sendo seguido à risca. Código retornado ao criar item no banco é [200](https://developer.mozilla.org/pt-BR/docs/Web/HTTP/Status/200), mas devia ser [201](https://developer.mozilla.org/pt-BR/docs/Web/HTTP/Status/201).

## Print

![image](https://user-images.githubusercontent.com/13920100/157348664-f0c3fd53-7358-474e-a595-f08423db7c5d.png)

## Suggestion

Mudar código HTTP retonado pelo método em: https://github.com/AndreonSM/notAutumn/blob/cae3ffde13d7ee48c3201889f0d6f10daeebbf9b/src/main/java/com/example/firstproject/controllers/UserController.java#L43

**Comment by AndreonSM** [comment]
Solução para mudar o código HTTP: 
Mudar o tipo do método **_addUser_** de _User_ para _ResponseEntity<User>_ e mudar o código HTTP diretamente no _return._ Consequentemente, a tipagem do mesmo deve ser modificada.

Print:
![Issue4](https://user-images.githubusercontent.com/54782540/157739114-fcafeea5-ccf8-4b24-b4cf-47a6cf025338.PNG)
